FROM python:3.12-slim

WORKDIR /

COPY src/sender.py /src/sender.py
COPY config/sender.yaml /config/sender.yaml
COPY config/libsender.txt /config/requirements.txt

RUN pip install -r /config/requirements.txt

EXPOSE 5000

ENTRYPOINT ["python", "/src/sender.py"]
