apiVersion: v1
kind: Service
metadata:
  name: receiver-svc
spec:
  selector:
    app: receiver
  ports:
    - protocol: TCP
      port: 5000        # Service port
      targetPort: 5000  # Container port
  type: ClusterIP
