apiVersion: v1
kind: Service
metadata:
  name: sender-svc
spec:
  selector:
    app: sender
  ports:
    - protocol: TCP
      port: 80        # Service port
      targetPort: 80  # Container port
  type: ClusterIP
